### ISSUE TITLE
Fails on @decorators

### ISSUE THREAD

**Issue by peterbe** [snowcoders/sci-sort-import-groups#7]
See screenshot:

<img width="1206" alt="screen shot 2018-09-19 at 4 39 10 pm" src="https://user-images.githubusercontent.com/26739/45780029-a2c0e900-bc2a-11e8-8669-b2fa41742232.png">

**Comment by k2snowman69** [comment]
Ooooh good catch! sci-sort-import-groups (which is now [deprecated](https://github.com/snowcoders/sci-sort-import-groups#deprecation-notice)) and sortier-vscode both rely on sortier. I've opened a bug on [sortier directly](https://github.com/snowcoders/sortier/issues/108) to investigate this issue. 

Note that the fix will likely only make it to sortier-vscode and not this extension because this extension has been deprecated for about 6 months now.

**Comment by peterbe** [comment]
The reason I came to sci-sort-import-groups was because it popped up on google search. I think I arrived on https://marketplace.visualstudio.com/items?itemName=Snowcoders.sci-sort-import-groups 

That README should really have a big fat link to https://github.com/snowcoders/sortier-vscode hint hint :)

**Comment by k2snowman69** [comment]
Alrighty, had to publish 2.1.1 but finally go the deprecation notice on there.
https://marketplace.visualstudio.com/items?itemName=Snowcoders.sci-sort-import-groups

I've also opened https://github.com/snowcoders/sortier/issues/109
 and https://github.com/snowcoders/sortier-vscode/issues/16 to look into the SEO issue. My guess is it has to do with the lack of information in the readme.

**Comment by k2snowman69** [comment]
Finally I added a unit test locally for decorators in https://github.com/snowcoders/sortier/issues/108 and attached the sample input and output for the test which succeeded. So hopefully Sortier works for you!

**Comment by k2snowman69** [comment]
Closing based on https://github.com/snowcoders/sortier/issues/108
